<?php
return [
	'app.js',
	'init.js',
	'services/api.js',
	'services/hash.js',
	'services/events.js',
	'services/bind.js',
	'services/deferred.js',
	'services/form.js',
	'services/local-jQuery.js',
	'transformations/tiny.js',
	'rendering/rendering.js',
	'rendering/templates.js',
	'rendering/jquery-tmpl-wrapper.js',
	'rendering/mustache-wrapper.js',
	'rendering/underscore-wrapper.js',
	'rendering/handlebars-wrapper.js',
];
